### PR TITLE
Reset state after line number token

### PR DESCRIPTION
**Pull request by ojwb**

### CODE REVIEW

**Comment by ojwb** [comment]
(I noticed just after pushing that someone else had opened an issue for this, so I've added a "Fixes" reference to the commit message and force pushed.)

**Comment by ojwb** [comment]
Is there anything I can do to help get this merged?

Ignoring the auto-reformatting commit (those changes were forced upon me by a git hook) this is a single line fix plus regression test which solves an annoying bug multiple people have run in to (it's been brought up on twitter a few times, as well as the issue reported here).

**Comment by ojwb** [comment]
I've pushed a commit which supresses the undesirable expansion of line number tokens inside strings, as demonstrated by this example:

https://twitter.com/P_Malin/status/1441075916545970184

**Comment by mattgodbolt** [comment]
hey hey! wow, sorry !!!! I'll take a look right now :blush:

**Review by mattgodbolt — APPROVED** [review]

**Pull request merged**
