### PR TITLE
Show BBC micro coordinates of mouse cursor

### PR DESCRIPTION
**Pull request by ojwb**
Handy when you want to know the coordinates to enter into your BASIC program to plot something at a particular position.

This pretty much works, but there seems to be some padding inside the "screen" canvas which I'm not sure how to correctly allow for so the coordinates are a little bit off (worse towards the lower left).

In text modes the coordinates are text coordinates.  Maybe we should show text and graphics coordinates in graphics modes.

### CODE REVIEW

**Comment by ojwb** [comment]
After some more digging and poking I still really have no idea where this screen margin is coming from, but I've added an adjustment by an empirically derived fudge factor and the coordinates now seem to line up nicely.

**Comment by 8bitkick** [comment]
this is a great idea. I have no idea about the magic behind the virtual beam as it paints the canvas in `video.js` of jsbeeb but that's where the margin lies.

**Comment by ojwb** [comment]
@8bitkick Gah, the massive reformatting of emulator.js while there are unmerged PRs which change that file was not helpful...

**Comment by mattgodbolt** [comment]
If the formatting was auto (which it _ought to be? maybe I didn't port that over from jsbeeb yet...) then this would be less a problem, sorry

**Comment by ojwb** [comment]
> I have no idea about the magic behind the virtual beam as it paints the canvas in video.js of jsbeeb but that's where the margin lies.

I see in video.js:

```
        this.topBorder = 12;
        this.bottomBorder = 13;
        this.leftBorder = 5 * 16;
        this.rightBorder = 3 * 16;
```

Lower down `1024 - this.rightBorder` and `625 - this.bottomBorder` are used, so it seems the canvas is expected to be 1024x625 pixels and that seems to be confirmed by looking at canvas.js.

That seems to mean the paintable area of the canvas is 1024-5*16-3*16=896 wide and 625-25=800 high, which seems too square.

Anyway, I think the empirically derived fudge factors will do but if someone who actually understands this wants to replace them with the correct formulae that'd be great.

I've rebased the branch.  I'll sort out reporting text and graphics coordinates and then this should be OK to merge.

**Comment by ojwb** [comment]
OK, ready to go now I think.

**Comment by 8bitkick** [comment]
Works great. I'm going to adjust layout a bit especially considering mobile (54% of Owlet sessions...) before we deploy it. Sorry for moving code underneath before...

**Comment by 8bitkick** [comment]
Hopefully this works for you @ojwb ... it did just occur to me you might want to see the time and coords simultaneously... I can find a way if you need it

**Comment by ojwb** [comment]
Is that counting "visits" rather than time actually spent using owlet?  I suspect that percentage overstates "real" usage (probably many of the mobile users are actually just clicking the source link from a post rather than really using owlet to write code).  I can see it makes sense to have it behave sensibly on a mobile device, but I'd be careful about making it less usable for desktop users.

I'm not sure I **need** to see both time and coordinates, but it may prove annoying for the timing to disappear if you happen to move the mouse pointer over the window.  I'll need to use it for a bit and see.

Some comments on the new look:

The "Run" button above the editor and the "play/pause" button above the emulator both use the same triangular play icon now, which seems confusing.  FWIW, I find the icons much less clear than the text labels and rather liked the echoes of BBC BASIC commands (NEW/RUN/SAVE) we had before.  Perhaps these icons should only be used on mobile?  There's plenty of space for the text buttons on desktop.

The "Save" button being above the editor suggests it's saving the source code, but it's really a way to save data from the **emulator** (that's why I put it under the emulator window).  Perhaps it should go with the buttons above the emulator window instead?

The "3D" button seems misplaced too now I think about it.  Logically it's very similar to the options to export as a tape or disc image (and like "post to mastodon" if we manage to reinstate that) so I'd put it above the editor window (all of these use the code that's currently in the editor window, not the code that's currently in the emulator - I just tested this for the 3D button by modifying the code in the emulator and clicking it).  The rocket button however is to do with the emulator so that makes sense where it is.

The new rocket icon doesn't scream "rocket" to me - the old rocket icon was much clearer, and (at least for me) matched the rocket emoji which helps to emphasise it's essentially the same thing.

**Pull request merged**
